OWP/Models/Book.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace OWP.Models
{
    public class Book
    {
        public int Id { get; set; }

        [Required]
        [StringLength(255)]
        public string Name { get; set; }

        public string Author { get; set; }

        [Display(Name = "Release Date")]
        public DateTime ReleaseDate { get; set; }

        [Display(Name = "Price")]
        [DataType(DataType.Currency)]
        public decimal Price { get; set; }

        public byte NumberInStock { get; set; }

    }
}

OWP/Controllers/BooksController.cs
using OWP.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PagedList;

namespace OWP.Controllers
{
    [Authorize]
    public class BooksController : Controller
    {

        public ApplicationDbContext _context;

        public BooksController()
        {
            _context = new ApplicationDbContext();
        }
        // GET: Books
        public ActionResult Index(string search, int? page)
        {
            int pageSize = 3;
            int pageNumber = page ?? 1;

            var books = _context.Books.AsQueryable();
                
            //from b in _context.Books select b;

            if (!String.IsNullOrEmpty(search))
            {
                books = books.Where(b => b.Name.Contains(search));
            }

            var pagedBooks = books
                .OrderBy(b => b.Id)
                .ToPagedList(pageNumber, pageSize);
            
            return View(pagedBooks);
        }

        public ActionResult Details(int id)
        {
            var book = _context.Books.FirstOrDefault(x => x.Id == id);
            if (book == null) return HttpNotFound();
            return View(book);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Book book)
        {
            if (ModelState.IsValid)
            {
                _context.Books.Add(book);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(book);
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            Book book = _context.Books.Find(id);

            if (book == null)
                return HttpNotFound();

            return View(book);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Book book)
        {
            if (ModelState.IsValid)
            {
                _context.Entry(book).State = System.Data.Entity.EntityState.Modified;
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(book);
                
        }

        public ActionResult Delete(int? id)
        {
            if(id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            Book book = _context.Books.Find(id);

            if (book == null)
                return HttpNotFound();

            return View(book);
        }
        
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Book book = _context.Books.Find(id);
            _context.Books.Remove(book);
            _context.SaveChanges();

            return RedirectToAction("Index");
        }
    }
}

OWP/Controllers/CartController.cs
using OWP.Helpers;
using OWP.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OWP.Controllers
{
    public class CartController : Controller
    {
        private readonly ApplicationDbContext _context = new ApplicationDbContext();
        public ActionResult Index()
        {
            var cart = CartSession.GetCart();
            return View(cart);
        }

        [HttpPost]
        public ActionResult Add(int bookId, int qty = 1)
        {
            var book = _context.Books.FirstOrDefault(b => b.Id == bookId);
            if (book == null) return HttpNotFound();

            var cart = CartSession.GetCart();
            var existing = cart.FirstOrDefault(x => x.BookId == bookId);

            if (existing != null) existing.Quantity += qty;
            else cart.Add(new OWP.Models.CartItem
            {
                BookId = book.Id,
                Title = book.Name,
                UnitPrice = (decimal)book.Price,
                Quantity = qty
            });

            return RedirectToAction("Index");
          
        }

        [HttpPost]
        public ActionResult Remove(int bookId)
        {
            var cart = CartSession.GetCart();
            var item = cart.FirstOrDefault(x => x.BookId == bookId);
            if (item != null) cart.Remove(item);

            return RedirectToAction("Index");
        }
    }
}

OWP/Views/Books/Create.cshtml
@model OWP.Models.Book
@{
    ViewBag.Title = "Create";
}

<h2>Dodavanje knjige</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div>
        @Html.LabelFor(m => m.Name)
        @Html.TextBoxFor(m => m.Name)
    </div>

    <div>
        @Html.LabelFor(m => m.Author)
        @Html.TextBoxFor(m => m.Author)
    </div>

    <div>
        @Html.LabelFor(m => m.ReleaseDate)
        @Html.TextBoxFor(m => m.ReleaseDate)
    </div>

    <div>
        @Html.LabelFor(m => m.Price)
        @Html.TextBoxFor(m => m.Price)
    </div>

    <div>
        @Html.LabelFor(m => m.NumberInStock)
        @Html.TextBoxFor(m => m.NumberInStock)
    </div>
    <button type="submit">Sačuvaj</button>
}

OWP/Views/Books/Delete.cshtml
@model OWP.Models.Book
@{
    ViewBag.Title = "Delete";
}

<h2>
    Brisanje knjige
</h2>

<h4>Da li ste sigurni da zelite da obrisete ovu knjigu?</h4>

<dl class="dl-horizontal">
    <dt>Naziv</dt>
    <dd>@Model.Name</dd>

    <dt>Autor</dt>
    <dd>@Model.Author</dd>

    <dt>Datum izdavanja</dt>
    <dd>@Model.ReleaseDate</dd>

    <dt>Cena</dt>
    <dd>@Model.Price</dd>

    <dt>Dostupnost</dt>
    <dd>@Model.NumberInStock</dd>
</dl>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(m => m.Id)

    <button type="submit" class="btn btn-danger">Obriši</button>
    @Html.ActionLink("Odustani", "Index", null, new { @class = "btn btn-secondary" })
}

OWP/Views/Books/Details.cshtml
@model OWP.Models.Book
@{
    ViewBag.Title = "Details";
}

<h2>Detalji knjige</h2>
<hr />

<dl class="dl-horizontal">
    <dt>Naziv knjige</dt>
    <dd>@Model.Name</dd>

    <dt>Autor knjige</dt>
    <dd>@Model.Author</dd>

    <dt>Godina izdavanja</dt>
    <dd>@Model.ReleaseDate</dd>

    <dt>Cena</dt>
    <dd>@Model.Price</dd>

    <dt>Dostupnost</dt>
    <dd>@Model.NumberInStock</dd>
</dl>

<p>
    @Html.ActionLink("Izmeni", "Edit", new {id = Model.Id}) |
    @Html.ActionLink("Nazad", "Index")
</p>

OWP/Views/Books/Edit.cshtml
@model OWP.Models.Book
@{
    ViewBag.Title = "Edit";
}

<h2>Izmena knjige</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(m => m.Id)

    <div class="form-group">
        @Html.LabelFor(m => m.Name)
        @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Name)
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.Author)
        @Html.TextBoxFor(m => m.Author, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Author)
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.ReleaseDate)
        @Html.TextBoxFor(m => m.ReleaseDate, new { @class = "form-control" })
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.Price)
        @Html.TextBoxFor(m => m.Price, new { @class = "form-control" })
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.NumberInStock)
        @Html.TextBoxFor(m => m.NumberInStock, new { @class = "form-control" })
    </div>

    <button type="submit" class="btn btn-success">Sačuvaj</button>
    @Html.ActionLink("Nazad", "Index", null, new{ @class = "btn btn-secondary"})
}

OWP/Views/Books/Index.cshtml
@using PagedList.Mvc;
@using PagedList;
@using System.Web.Mvc
@model IPagedList<OWP.Models.Book>

<h2>Lista knjiga</h2>

<p>
    @Html.ActionLink("Dodajte novu knjigu", "Create")
</p>

@using (Html.BeginForm("Index", "Books", FormMethod.Get))
            {
                <input type="text" name="search" placeholder="Search by title" class="form-control"/>
                <button type="submit" class="btn btn-primary">Search</button>
            }
<table class="table">
    <thead>
        <tr>
            <th>Naziv</th>
            <th>Autor</th>
            <th>Godina</th>
            <th>Cena</th>
            <th>Dostupno</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach(var item in Model)
            {
        <tr>
            <td>@item.Name</td>
            <td>@item.Author</td>
            <td>@item.ReleaseDate</td>
            <td>@item.Price</td>
            <td>@item.NumberInStock</td>
            <td>
                @Html.ActionLink("Detalji", "Details", new { id = item.Id }) |
                @Html.ActionLink("Izmeni", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Obrisi", "Delete", new { id = item.Id })

                @using (Html.BeginForm("Add", "Cart", FormMethod.Post, new {style = "display:inline" }))
                {
                    @Html.Hidden("bookId", item.Id)
                    <button type="submit" class="btn btn-sm btn-success" title="Dodaj u korpu">
                        <i class="fa fa-cart-plus"></i>
                    </button>

                }
            </td>
        </tr>
            }
        
    </tbody>
</table>

<div class="text-center">
    @Html.PagedListPager(
       Model,
       page => Url.Action("Index", new { page = page, search = Request.QueryString["search"] })

   )
</div>